client:
  function-key: ${cdrClient.functionKey:}
  local-folder: ${cdrClient.localFolder:${java.io.tmpdir}/cdr_download}
  schedule-delay: PT10M
  files-in-progress-cache-size: 10MB
  connection-timeout-ms: 5000
  #we want the read timeout to be longer than a connection timeout between backend and db
  read-timeout-ms: 35000
  # max number of connectors to be processed in parallel, one download per connector at any given time
  pull-thread-pool-size: 5
  # max number of parallel document uploads (independent of connector)
  push-thread-pool-size: 5
  retry-delay:
    - 1s
    - 2s
    - 8s
    - 32s
    - 10m
  endpoint:
    scheme: https
    port: 443
    #       host: dev-cdr-functions.azurewebsites.net
    base-path: documents
  customer:
  #  MUST BE SET IN ENVIRONMENT
  #   - connector-id: 1
  #     content-type: application/forumdatenaustausch+xml;charset=UTF-8;version=4.5
  #     target-folder: /tmp/download
  #     source-folder: /tmp/upload
  #     mode: test|production
