client:
  schedule-delay: PT30S
  local-folder: ${CDR_CLIENT_LOCAL_FOLDER:${HOME}/Documents/cdr/inflight}
  idp-credentials:
    scopes:
      - https://dev.identity.health.swisscom.ch/CdrApi/.default
    renew-credential-at-startup: false
    client-secret: ${CDR_CLIENT_SECRET:Placeholder_test-secret}
  cdr-api:
    scheme: http
    port: 9090
    host: localhost
    base-path: documents
  credential-api:
    base-path: client-credentials
  retry-template:
    retries: 1
  customer:
    - connector-id: 1
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[0].connector-id}/test
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test
      mode: test
    - connector-id: 1
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[1].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[1].connector-id}
      mode: production
    - connector-id: 1234
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[2].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[2].connector-id}
      mode: test
    - connector-id: 5
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[3].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[3].connector-id}
      mode: test
    - connector-id: 666
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[4].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[4].connector-id}
      mode: production
    - connector-id: 2345
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[5].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[5].connector-id}
      mode: production
