client:
  local-folder: ${java.io.tmpdir}/swisscom/in-flight # temporary folder for files that are currently downloaded from CDR API
  idp-credentials:
    tenant-id: not-set # provided by Swisscom Health
    client-id: not-set # Self created through CDR UI
    client-secret: not-set # Self created through CDR UI
  endpoint:
    host: cdr.health.swisscom.ch
  customer:
    - connector-id: 8000000000000 # provided by Swisscom Health
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${java.io.tmpdir}/swisscom/download/test/8000000000000
      source-folder: ${java.io.tmpdir}/swisscom/upload/test/8000000000000
      mode: test
    - connector-id: 8000000000000 # provided by Swisscom Health
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${java.io.tmpdir}/swisscom/download/8000000000000
      source-folder: ${java.io.tmpdir}/swisscom/upload/8000000000000
      mode: production
