services:
  wiremock:
    image: local.wiremock.cdrapi
    container_name: cdr-client-wiremock
    build: ./wiremock
    mem_limit: 256m
    healthcheck:
      # use a mapped URL for health checking; the response is a 200 OK with a string body "OK"
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
        - "9090:8080"
    environment:
      - TZ=Europe/Zurich
    command: ["--verbose", "--global-response-templating"]
    networks:
      - cdr_client_net

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.2.1
    container_name: cdr-client-mock-oauth2-server
    environment:
      - TZ=Europe/Zurich
      - LOG_LEVEL=DEBUG
      - JSON_CONFIG_PATH=/app/config.json
      - SERVER_PORT=8080
    volumes:
      - ./mockOAuth2Server/config.json:/app/config.json
    networks:
      - cdr_client_net

  caddy:
    depends_on:
      wiremock:
        condition: service_healthy
      mock-oauth2-server:
        condition: service_started
    image: local.caddy.cdrclient
    container_name: cdr-client-caddy
    build: ./caddy
    mem_limit: 256m
    ports:
      - "443:8443"
      - "80:8080"
    healthcheck:
      # checks the mock-oauth2-server's health endpoint to prove that both caddy and the mock-oauth2-server are up and running
      test: curl --fail http://localhost:8080/isalive || exit 1
      interval: 5s
      retries: 5
      start_period: 120s
      timeout: 10s
    networks:
      - cdr_client_net

networks:
  cdr_client_net:
    name: cdr_client_net
    ipam:
      config:
        - subnet: 10.113.0.0/16
