client:
  local-folder: /tmp/download/in-flight # temporary folder for files that are currently downloaded from CDR API
  idp-credentials:
    tenant-id: no-tenant-id # provided by Swisscom Health
    client-id: no-client-id # Self created through CDR UI
    client-secret: no-client-secret # Self created through CDR UI
  endpoint:
    host: cdr.health.swisscom.ch
  customer:
    - connector-id: 8000000000000 # provided by Swisscom Health
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: /tmp/download/test/8000000000000
      source-folder: /tmp/upload/test/8000000000000
      mode: test
    - connector-id: 8000000000000 # provided by Swisscom Health
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: /tmp/download/8000000000000
      source-folder: /tmp/upload/8000000000000
      mode: production
