client:
  local-folder: ${cdrClient.localFolder:${java.io.tmpdir}/cdr_download}
  idp-credentials:
    tenant-id: ${CDR_B2C_TENANT_ID:no-token}
    client-id: ${CDR_CLIENT_ID:id}
    client-secret: ${CDR_CLIENT_SECRET:dummy}
    scopes:
      - https://${CDR_CLIENT_SCOPE_PREFIX:}identity.health.swisscom.ch/CdrApi/.default
  idp-endpoint: https://login.microsoftonline.com/${client.idp-credentials.tenant-id}/
  schedule-delay: PT10M
  files-in-progress-cache-size: 10MB
  connection-timeout-ms: 5000
  #we want the read timeout to be longer than a connection timeout between backend and db
  read-timeout-ms: 35000
  # max number of connectors to be processed in parallel, one download per connector at any given time
  pull-thread-pool-size: 5
  # max number of parallel document uploads (independent of connector)
  push-thread-pool-size: 5
  retry-delay:
    - 1s
    - 2s
    - 8s
    - 32s
    - 10m
  endpoint:
    scheme: https
    port: 443
    host: cdr.health.swisscom.ch
    base-path: api/documents
  customer:
  #  MUST BE SET IN ENVIRONMENT
  #   - connector-id: 1
  #     content-type: application/forumdatenaustausch+xml;charset=UTF-8
  #     target-folder: /tmp/download
  #     source-folder: /tmp/upload
  #     mode: test|production
