client:
  file-synchronization-enabled: true
  local-folder: ${java.io.tmpdir}
  idp-credentials:
    tenant-id: blah
    client-id: blah
    client-secret: blah
    scopes:
      - https://identity.health.swisscom.ch/CdrApi/.default
    renew-credential: false
    max-credential-age: 365d
    last-credential-renewal-time: 1970-01-01T00:00:00Z
  file-busy-test-interval: 250ms
  file-busy-test-timeout: 30s
  file-busy-test-strategy: file_size_changed # valid values are `never_busy`, `file_size_changed`, `always_busy`
  cdr-api:
    scheme: https
    port: 443
    host: cdr.health.swisscom.ch
    base-path: api/documents
  credential-api:
    scheme: ${client.cdr-api.scheme}
    port: ${client.cdr-api.port}
    host: ${client.cdr-api.host}
    base-path: api/client-credentials
  customer:
    - connector-id: 1
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[0].connector-id}/test
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test
      source-error-folder: errors
      source-archive-folder: archive
      mode: test
      doc-type-folders:
        invoice:
          target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[0].connector-id}/test/invoice
          source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test/invoice
        credit:
          source-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test/credit